### ISSUE TITLE
Project2 Code Review Issue

### ISSUE THREAD

**Issue by RuilingZ** [CalebMeriga/project-2#1]
It's a nice work!

1.It has detailed user story and MVP that make the project easy to understand. It has a clear and complete project framework, making projects easy to read. I like your clean and effective code.
2.The tweet to be analyzed can be selected. That makes it easier to match different users' requirements.
3.If the tweet is in different language it translates that tweet into english using "Google cloud Translate". This is a very creative point and inspire me a lot.

The project is good, and I only have a few suggestion.

1.It seems that there are few comment, so it's a bit hard to read for those unfamiliar with the code. So more comments may be better.
2.The project only analyzed one tweet, perhaps it would be better to analyze multiple tweets. Maybe users want to know the person's general attitude to life.
3.Based on the average score, the output will be "GOOD" or "OK" or "BAD", it's clear. But it may be better if the tweets can also be printed. Apart from the analysis result, the user may also want to check the tweet.

**Comment by CalebMeriga** [comment]
Thank you very much for commenting and providing Suggestions,
1.I will add more comments to improve readability. 
2.The code can analyze 0-200 tweets per username(can be found in bottom of  "Final Project 2 Code and [Outpu.txt")

3.The tweets are printed before translation and translated version along with the score of the tweet.(can be found in bottom of  "Final Project 2 Code and [Outpu.txt").

https://github.com/CalebMeriga/project-2/blob/214a133fc574875e2f997de3ce0aad61f415009a/Final%20Project%202%20Code%20and%20Outpu.txt

Hope these clarify your doubts, I  apologize if I misunderstood any suggestions of yours.
